# Generated by Django 5.2.17 on 2026-09-28 14:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_experience_starred_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='starred_by',
            field=models.ManyToManyField(blank=True, related_name='starred_educations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='education',
            name='degree',
            field=models.CharField(choices=[('high_school', 'High School'), ('undergraduate', 'Undergraduate'), ('postgraduate', 'Postgraduate'), ('certification', 'Certification / Course')], default='undergraduate', max_length=50),
        ),
    ]
